/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoadingIndicator: typeof import('./src/crudui/components/templates/AppLoadingIndicator.vue')['default']
    AppSelect: typeof import('./src/crudui/components/app-form-elements/AppSelect.vue')['default']
    AppStepper: typeof import('./src/crudui/components/templates/AppStepper.vue')['default']
    ButtonAction: typeof import('./src/crudui/components/table/buttons/ButtonAction.vue')['default']
    ButtonBatchDelete: typeof import('./src/crudui/components/table/buttons/ButtonBatchDelete.vue')['default']
    CenteredContentWrapper: typeof import('./src/crudui/components/templates/CenteredContentWrapper.vue')['default']
    CreateButton: typeof import('./src/crudui/components/buttons/CreateButton.vue')['default']
    CrudBooleanSelect: typeof import('./src/crudui/components/Inputs/CrudBooleanSelect.vue')['default']
    CrudButtonPrimary: typeof import('./src/crudui/components/buttons/CrudButtonPrimary.vue')['default']
    CrudButtonSecondary: typeof import('./src/crudui/components/buttons/CrudButtonSecondary.vue')['default']
    CrudCheckbox: typeof import('./src/crudui/components/Inputs/CrudCheckbox.vue')['default']
    CrudConfirmDialog: typeof import('./src/crudui/components/dialogs/CrudConfirmDialog.vue')['default']
    CrudDatePicker: typeof import('./src/crudui/components/Inputs/CrudDatePicker.vue')['default']
    CrudDateRangePicker: typeof import('./src/crudui/components/Inputs/CrudDateRangePicker.vue')['default']
    CrudDateRangePicker2: typeof import('./src/crudui/components/Inputs/CrudDateRangePicker2.vue')['default']
    CrudDialog: typeof import('./src/crudui/components/dialogs/CrudDialog.vue')['default']
    CrudEditForm: typeof import('./src/crudui/components/forms/CrudEditForm.vue')['default']
    CrudInput: typeof import('./src/crudui/components/Inputs/CrudInput.vue')['default']
    CrudMoney: typeof import('./src/crudui/components/Inputs/CrudMoney.vue')['default']
    CrudSelect: typeof import('./src/crudui/components/Inputs/CrudSelect.vue')['default']
    CrudSelector: typeof import('./src/crudui/components/Inputs/CrudSelector.vue')['default']
    CrudTable: typeof import('./src/crudui/components/table/CrudTable.vue')['default']
    CustomRadios: typeof import('./src/crudui/components/app-form-elements/CustomRadios.vue')['default']
    DefaultLayoutWithHorizontalNav: typeof import('./src/crudui/components/templates/DefaultLayoutWithHorizontalNav.vue')['default']
    DefaultLayoutWithVerticalNav: typeof import('./src/crudui/components/templates/DefaultLayoutWithVerticalNav.vue')['default']
    DialogCloseBtn: typeof import('./src/crudui/components/dialogs/DialogCloseBtn.vue')['default']
    DropZone: typeof import('./src/crudui/components/DropZone.vue')['default']
    ErrorHeader: typeof import('./src/crudui/components/templates/ErrorHeader.vue')['default']
    HorizontalNav: typeof import('./src/crudui/components/templates/navigation/horizontal/HorizontalNav.vue')['default']
    HorizontalNavGroup: typeof import('./src/crudui/components/templates/navigation/horizontal/HorizontalNavGroup.vue')['default']
    HorizontalNavLayout: typeof import('./src/crudui/components/templates/navigation/horizontal/HorizontalNavLayout.vue')['default']
    HorizontalNavLink: typeof import('./src/crudui/components/templates/navigation/horizontal/HorizontalNavLink.vue')['default']
    HorizontalNavPopper: typeof import('./src/crudui/components/templates/navigation/horizontal/HorizontalNavPopper.vue')['default']
    LanguageSwitcher: typeof import('./src/crudui/components/LanguageSwitcher.vue')['default']
    MoreBtn: typeof import('./src/crudui/components/MoreBtn.vue')['default']
    NotificationSystem: typeof import('./src/crudui/components/templates/NotificationSystem.vue')['default']
    PageTitle: typeof import('./src/crudui/components/templates/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/crudui/components/ScrollToTop.vue')['default']
    TransitionExpand: typeof import('./src/crudui/components/templates/TransitionExpand.vue')['default']
    UserProfile: typeof import('./src/crudui/components/templates/UserProfile.vue')['default']
    VerticalNav: typeof import('./src/crudui/components/templates/navigation/vertical/VerticalNav.vue')['default']
    VerticalNavGroup: typeof import('./src/crudui/components/templates/navigation/vertical/VerticalNavGroup.vue')['default']
    VerticalNavLayout: typeof import('./src/crudui/components/templates/navigation/vertical/VerticalNavLayout.vue')['default']
    VerticalNavLink: typeof import('./src/crudui/components/templates/navigation/vertical/VerticalNavLink.vue')['default']
    VerticalNavSectionTitle: typeof import('./src/crudui/components/templates/navigation/vertical/VerticalNavSectionTitle.vue')['default']
  }
}
